name: Build Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: windows-latest 

    strategy:
      matrix: 
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Electron Builder Action
      uses: Yan-Jobs/action-electron-builder@v1.7.0
      with: 
            args: --ia32 --publish always
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            release: ${{ startsWith(github.ref, 'refs/tags/v') }}
